### ISSUE TITLE
Pluto ipsec.secret syntax                        INTERNAL ERROR - unknown rcode:WARNING

### ISSUE THREAD

**Issue by bit4woo** [Teddysun/across#10]
`erifying installed system and configuration files

Version check and ipsec on-path                   	[OK]
Libreswan 3.20 (netkey) on 4.4.0-63-generic
Checking for IPsec support in kernel              	[OK]
 NETKEY: Testing XFRM related proc values
         ICMP default/send_redirects              	[OK]
         ICMP default/accept_redirects            	[OK]
         XFRM larval drop                         	[OK]
Pluto ipsec.conf syntax                           	[OK]
Two or more interfaces found, checking IP forwarding	[OK]
Checking rp_filter                                	[OK]
Checking that pluto is running                    	[OK]
 Pluto listening for IKE on udp 500               	[OK]
 Pluto listening for IKE/NAT-T on udp 4500        	[OK]
 Pluto ipsec.secret syntax                        INTERNAL ERROR - unknown rcode:WARNING
  003 WARNING: using a weak secret (PSK)
Checking 'ip' command                             	[OK]
Checking 'iptables' command                       	[OK]
Checking 'prelink' command does not interfere with FIPS	[OK]
Checking for obsolete ipsec.conf options          	[OK]
`
any resolution or method to debug for this issue? thanks.

**Comment by Teddysun** [comment]
WARNING: using a weak secret (PSK)

PSK too simple, that is the reason.

**Comment by bit4woo** [comment]
yes, you are right.

I change the PSK value to a longer string by edit /etc/ipsec.secrets, and the error disappear.

thanks very much!
