### ISSUE TITLE
/boot/grub/grub.conf not found 和 /boot/grub2/grub.cfg not found 问题

### ISSUE THREAD

**Issue by maicong** [teddysun/across#15]
下面方法可以解决，希望作者可以添加到安装脚本里。

`/boot/grub/grub.conf` 缺失：
```shell
yum install -y grub
grub-mkconfig -o /boot/grub/grub.conf
```
`/boot/grub2/grub.cfg` 缺失：
```shell
yum install -y grub2
grub2-mkconfig -o /boot/grub2/grub.cfg
```

**Comment by davidan106** [comment]
请问下 如果yum源里面没有grub和grub2的话应该怎么办？

**Comment by maicong** [comment]
换下 repo？例如阿里的镜像源里就有：
https://mirrors.aliyun.com/centos/6/os/x86_64/Packages/grub-0.97-99.el6.x86_64.rpm 
https://mirrors.aliyun.com/centos/7/os/x86_64/Packages/grub2-2.02-0.64.el7.centos.x86_64.rpm

换 repo 方法：http://mirrors.aliyun.com/help/centos

**Comment by davidan106** [comment]
配置镜像源，并清缓存了，但是还是会无法安装。。
![image](https://user-images.githubusercontent.com/25627232/33307404-4ef3a32e-d451-11e7-98b2-2963b5d6d5e8.png)
然后直接rpm安装会报一个很奇怪的依赖问题：
![image](https://user-images.githubusercontent.com/25627232/33307478-9601491a-d451-11e7-87a2-0388393d378c.png)

**Comment by maicong** [comment]
你的是什么版本的 Centos，只有 7 才有 grub2

**Comment by davidan106** [comment]
用的是Centos7.2 x64
