### ISSUE TITLE
搬瓦工centos7 bbr装完之后直接ssh连不上

### ISSUE THREAD

**Issue by tiantao433** [teddysun/across#18]
搬瓦工centos7 bbr装完之后直接ssh连不上

**Comment by ECIZEP** [comment]
vultr 也是bbr安装之后，ssh 22端口被关闭

**Comment by teddysun** [comment]
你首先需要确认 VPS 是否处于启动中，一般可以在 VNC 界面里看到。
bbr 脚本是不会修改 ssh 默认端口的。

**Comment by ECIZEP** [comment]
试了好几次，后台显示状态是running，我restart也不行，只有reinstall 才能用ssh 22端口连上机器。。

**Comment by ECIZEP** [comment]
VNC一直是连不上的状态，无论是否安装bbr，所以卡在开机的某一步就直接导致不reinstall就GG

**Comment by teddysun** [comment]
你需要打开 VNC 看看是不是真正启动成功了，而不仅仅是看面板上显示为 running，很有可能是内核安装后启动失败导致的。我建议你安装 Debian 9 系统，这样的话不用安装新内核就能开启 bbr 了。
还有就是，搬瓦工的默认 ssh 端口不是 22，而是随机产生的。

**Comment by SoDa-GitHub** [comment]
搬瓦工的有自带bbr的centos7

**Comment by ECIZEP** [comment]
OK 解决了，我是vultr的机器，我换了一个网络环境，然后连上VNC发现是卡在开机了，直接换centos 6 就不会卡在开机了

**Comment by jmxct520** [comment]
大佬，BBR安装以后，google访问到了，是挺快的，但是油管和维基百科访问不到啊

**Comment by melono-cn** [comment]
你可以试一下阿里云 香港ECS主机，免费用一个月。延迟 50MS以下，不过有封IP风险。搬瓦工的我没有用过。不太清楚。


------------------
感谢您长期对麦浪网浪服务的支持与厚爱，顺祝商祺！
                                                                 麦浪网浪服务！


 




------------------ 原始邮件 ------------------
发件人: "jmxct520"<notifications@github.com>;
发送时间: 2019年9月9日(星期一) 下午4:00
收件人: "teddysun/across"<across@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: Re: [teddysun/across] 搬瓦工centos7 bbr装完之后直接ssh连不上 (#18)




大佬，BBR安装以后，google访问到了，是挺快的，但是油管和维基百科访问不到啊
