### ISSUE TITLE
bench.sh的一个运行问题

### ISSUE THREAD

**Issue by davidan106** [teddysun/across#23]
运行系统环境:CentOS release 6.9 (Final)
内核版本:4.9.75-30.el6.x86_64
使用脚本:Bench.sh
出现的问题:在运行时会出现ping -4命令不存在的问题
![tim 20180430225925](https://user-images.githubusercontent.com/25627232/39434205-73e89f44-4cca-11e8-8a41-0466d93409e2.png)
PS:CentOS 7系统下运行正常

**Comment by teddysun** [comment]
Thanks for you issues.
Fixed.
