### ISSUE TITLE
Debian 8运行bbr.sh后显示Kernel panic

### ISSUE THREAD

**Issue by ziqizh** [teddysun/across#24]
运行bbr.sh后reboot后显示Kernel panic - not syncing: VPS: Unablt to mount root fswn-block.
请问如何解决呢？
谢谢！

**Comment by snowflakepw** [comment]
秋水我个人认为最成功的的地方就是，它从使用者的角度写了很多判断并且dpkg   update-grub   一气呵成。
然后issue那个的话，可能是内核锁定还是什么原因，建议更换系统。
