### ISSUE TITLE
bench.sh统计硬盘容量BUG

### ISSUE THREAD

**Issue by wsk170** [teddysun/across#26]
我在Vultr的VPS上搭了一个debian的系统。
df 命令里有udev的字段，但是我看了下脚本的代码没有过滤掉。
显示是这样的：
<img width="390" alt="image" src="https://user-images.githubusercontent.com/10161173/41664318-0b72dcb4-74d8-11e8-8ea9-95d1addadae2.png">
自己添加了过滤udev字段后，显示正常。
disk_size1=($( LANG=C df -hPl | grep -wvE '\-|none|tmpfs|devtmpfs|by-uuid|chroot|Filesystem|udev' | awk '{print $2}' ))
disk_size2=($( LANG=C df -hPl | grep -wvE '\-|none|tmpfs|devtmpfs|by-uuid|chroot|Filesystem|udev' | awk '{print $3}' ))
<img width="357" alt="image" src="https://user-images.githubusercontent.com/10161173/41664348-20822d3a-74d8-11e8-8ccc-c74ace8793ac.png">

**Comment by teddysun** [comment]
Fixed.
Thanks for your feedback.
