### ISSUE TITLE
Bench.sh 显示硬盘容量问题

### ISSUE THREAD

**Issue by davidan106** [teddysun/across#27]
运行系统环境:CentOS 7.4.1708
内核版本:4.13.12-1.el7.elrepo.x86_64
使用脚本:Bench.sh
出现的问题:在部分主机上，硬盘容量统计会报语法错误
![tim 20180626220819](https://user-images.githubusercontent.com/25627232/41917783-a7d0c828-798d-11e8-81f5-1840f817dfc3.png)
硬盘情况如下:
![image](https://user-images.githubusercontent.com/25627232/41917889-c9eb2516-798d-11e8-9d51-fe379af0fb52.png)
和正常显示的机器对比，发现/dev下仅有一个挂载硬盘时不会出现语法报错，而有2个(或以上)挂载硬盘时，就会出现类似上面的语法报错。

**Comment by teddysun** [comment]
正确的打开姿势是:
wget -qO- bench.sh | bash

注意，bash 和 sh 是有区别的。

**Comment by davidan106** [comment]
试了下wget -qO- bench.sh | bash 好像还是有这个问题
![image](https://user-images.githubusercontent.com/25627232/41924284-2858df22-799c-11e8-9391-4b9dd3d2b59e.png)

**Comment by teddysun** [comment]
Thanks for your feedback.
Fixed.
