### ISSUE TITLE
ubuntu 18.04.1 lts 上貌似有点小bug

### ISSUE THREAD

**Issue by jearol** [teddysun/across#29]
1，libreswan已经有deb包了，直接 apt install libreswan 就行
2，配置完 /etc/ipsec.conf 之后，没有正确加载 l2tp-psk-nonat，需要调整一下配置或者执行命令 ipsec auto --add l2tp-psk-nonat 确认加载

**Comment by teddysun** [comment]
建议使用我做的 Docker 镜像，目前已更新到 libreswan 的最新版。
详见：https://teddysun.com/536.html
以及：https://hub.docker.com/r/teddysun/l2tp/
