### ISSUE TITLE
Vultr Centos7重启后Xshell连接不上

### ISSUE THREAD

**Issue by Mustard404** [teddysun/across#30]
错误如下：
WARNING! The remote SSH server rejected X11 forwarding request.
Last login: Sun Nov 11 13:23:33 2018
/bin/bash: Permission denied
Connection closing...Socket close.

Connection closed by foreign host.

Disconnected from remote host(新建会话) at 21:24:00.

Type `help' to learn how to use Xshell prompt.
后台VNC连接输入账号密码重启跳回登入界面
![image](https://user-images.githubusercontent.com/14071947/48313489-5675a200-e5f8-11e8-8556-a4a88d8cd18f.png)

**Comment by teddysun** [comment]
你这个截图不是正常启动了么？

**Comment by Mustard404** [comment]
> 你这个截图不是正常启动了么？

启动正常了，登入上不去，输入账号密码就跳回这个页面  bbr

**Comment by teddysun** [comment]
在面板里找到你的 root 密码，使用 xshell 连接不就完了么。
这个画面就是一切正常，等待连接。

**Comment by Mustard404** [comment]
> 在面板里找到你的root密码，使用xshell连接不就完了么。
> 这个画面就是一切正常，等待连接。

Xshell连接报错/bin/bash: Permission denied
Connection closing...Socket close.

Connection closed by foreign host.

**Comment by tcc521** [comment]
xshell 上不去  国内的话ip被ban了吧  换台机子试下

**Comment by Mustard404** [comment]
> xshell上不去国内的话ip被禁了吧换台机子试下

不是被Ban了，Ban的话地址端口都不通了，一直提示账号密码不正确，不知道哪里出问题了，后来这机器快到期了。没用
