### ISSUE TITLE
在Ubuntu18.04下编译unixbench报错

### ISSUE THREAD

**Issue by hsl727261250** [teddysun/across#46]
`
gcc -o ./pgms/arithoh -DTIME -Wall -pedantic -ansi -O2 -fomit-frame-pointer -fforce-addr -ffast-math -Wall -Darithoh ./src/arith.c
./src/arith.c:32:10: fatal error: stdio.h: No such file or directory
 #include <stdio.h>
          ^~~~~~~~~
compilation terminated.
Makefile:185: recipe for target 'pgms/arithoh' failed
`
16.04下编译没问题, 有可能是gcc版本的问题, 暂时提个issue, 等我有空检查一下原因.

**Comment by luckycat0426** [comment]
`bash
sudo apt-get install libc6-dev
`
安装libc6即可解决
