### ISSUE TITLE
l2tp2.sh:行652: ipsec: 未找到命令

### ISSUE THREAD

**Issue by jesusslim** [teddysun/across#48]
l2tp.sh 执行完出现./l2tp2.sh:行652: ipsec: 未找到命令

**Comment by jesusslim** [comment]
环境是亚马逊ec2

**Comment by teddysun** [comment]
脚本已经不再更新了。建议使用 Docker Image 构建 L2TP/IPSec VPN
还有，最好不要在 EC2，Azure，GCE 等没有直接把公网 IP 设置到网卡的这种 VPS 上安装和使用镜像。
