### ISSUE TITLE
l2tpd 子网掩码如何设置

### ISSUE THREAD

**Issue by lihua123569** [teddysun/across#50]
L2tpd subnet mask setting: I install l2tpd.sh to execute the script. After the VPN server is enabled, the subnet mask is 255.255.255.255

This subnet mask is wrong. It should be 255.0.0.0 according to the principle

Can this be configured? Hurry!!

l2tpd 子网掩码设置：我安l2tpd.sh执行脚本，vpn服务端开启后，子网掩码255.255.255.255
这个子网掩码不对，按道理应该是255.0.0.0  
这个可以配置吗，着急！！

**Comment by teddysun** [comment]
脚本已经不再更新了。
建议使用 Docker Image 构建 L2TP/IPSec VPN，子网掩码设置可以参考：
https://hub.docker.com/r/teddysun/l2tp
还有，最好不要在 EC2，Azure，GCE 等没有直接把公网 IP 设置到网卡的这种 VPS 上安装和使用镜像。
