### ISSUE TITLE
GeoLite2 不再提供开放式公共下载服务

### ISSUE THREAD

**Issue by narky** [teddysun/across#53]
https://github.com/teddysun/across/blob/d984be07cccf6ea918db28d598e88ce0cecc6d3b/docker/v2ray/Dockerfile#L27

Starting December 30, 2019, we will be requiring users of our GeoLite2 databases to register for a MaxMind account and obtain a license key in order to download GeoLite2 databases. We will continue to offer the GeoLite2 databases without charge, and with the ability to redistribute with proper attribution and in compliance with privacy regulations. In addition, we are introducing a new end-user license agreement to govern your use of the GeoLite2 databases. Previously, GeoLite2 databases were accessible for download to the public on our developer website and were licensed under the Creative Commons Attribution-ShareAlike 4.0 International License.

Starting December 30, 2019, downloads will no longer be served from our public GeoLite2 page, from geolite.maxmind.com/download/geoip/database/*, or from any other public URL. See the section below for steps on how to migrate to the new download mechanism.

**Comment by teddysun** [comment]
还真是……
有替代方案么？

**Comment by narky** [comment]
稍等，我写个pull request

**Comment by teddysun** [comment]
> 稍等，我写个pull request

好的，有劳了

**Comment by narky** [comment]
PR 已提交，请大佬惠存

**Comment by teddysun** [comment]
https://github.com/teddysun/across/pull/54 里写的：
> 注册 maxmind的账号，并生成自己的license_key

这样太麻烦了，干脆写一个脚本自动下载到我自己的服务器上，然后将这个网址改为我的服务器地址好了

**Comment by teddysun** [comment]
我自己注册了个帐号，生成了 License key，然后又写了个 cron 脚本，每周自动去下载最新版。
下载地址为：
https://dl.lamp.sh/files/GeoLite2-Country-CSV.zip

**Comment by narky** [comment]
你的脚本你做主😂

**Comment by teddysun** [comment]
现在已经改为直接从官方 repo 直接下载 geoip.dat，不再编译生成。
