### ISSUE TITLE
WireGuard脚本无法安装内核

### ISSUE THREAD

**Issue by w311ang** [teddysun/across#56]
Debian 10.0 64bit
> root@localhost:~# /opt/wireguard.sh -r
[Thu 06 Feb 2020 08:12:30 AM PST] Check OS version
[Thu 06 Feb 2020 08:12:30 AM PST] Install wireguard from repository
[Thu 06 Feb 2020 08:12:30 AM PST] apt-get update
[Thu 06 Feb 2020 08:12:35 AM PST] apt-get -y install linux-headers-4.19.0-5-amd64
E: Unable to locate package linux-headers-4.19.0-5-amd64
E: Couldn't find any package by glob 'linux-headers-4.19.0-5-amd64'
E: Couldn't find any package by regex 'linux-headers-4.19.0-5-amd64'
[Thu 06 Feb 2020 08:12:36 AM PST] Execution command (apt-get -y install linux-headers-4.19.0-5-amd64) failed, please check it and try again.

仓库里只有`linux-headers-4.19.0-6-amd64`这个包吧。

**Comment by teddysun** [comment]
先升级内核到最新版本，重启后再次运行脚本

**Comment by w311ang** [comment]
> 先升级内核到最新版本，重启后再次运行脚本

谢谢，安装成功了。原来`apt upgrade`更新内核之后还要重启。
