### ISSUE TITLE
老哥我安装你的l2tp成功后,连接会导致服务器重启,请问该怎么办

### ISSUE THREAD

**Issue by 1099446868** [teddysun/across#58]
centos7的系统,没有安装在docker中,直接安装的,然后用win10连接会导致服务器重启

**Comment by teddysun** [comment]
这种VPN已经不推荐使用了。
如果你是一定要用VPN，推荐 Wireguard，简单方便。
至于你遇到的问题，从描述来看，无法得知真正原因，建议重新安装系统😂

**Comment by 1099446868** [comment]
服务器上有很多别的服务需要工作,不能重新安装系统,这个能卸载么?
