### ISSUE TITLE
docker pull latest 部署 ipsec无法启动

### ISSUE THREAD

**Issue by Sajotim** [teddysun/across#68]
docker logs l2tp正常
ipsec status报错
whack: is Pluto running?  connect() for "/run/pluto/pluto.ctl" failed (111 Connection refused)
重启ipsec无法解决
连接不上 提示无响应 确认400 4000udp均已开放

**Comment by teddysun** [comment]
目前遇到一个不好解决的 bug，问题出在 alpine 编译的版本和 nss 有冲突。
建议使用上一个版本的 tag 来试试看，也就是 `docker pull teddysun/l2tp:3.31`
如果还是不行的话，建议直接使用 [wireguard](https://teddysun.com/554.html)
