### ISSUE TITLE
"libsystemd-dev" needed instead of  "libsystemd-daemon-dev" on  ubuntu 16.4

### ISSUE THREAD

**Issue by bit4woo** [Teddysun/across#9]
when I use your script on Ubuntu 16.04.2 LTS, I got the following error:

`In file included from /root/l2tp/libreswan-3.19/programs/pluto/plutomain.c:103:0:
/root/l2tp/libreswan-3.19/programs/pluto/pluto_sd.h:22:31: fatal error: systemd/sd-daemon.h: No such file or directory
compilation terminated.
../../../mk/depend.mk:28: recipe for target 'plutomain.o' failed
make[3]: *** [plutomain.o] Error 1
make[3]: Leaving directory '/root/l2tp/libreswan-3.19/OBJ.linux.x86_64/programs/pluto'
Makefile:456: recipe for target 'local-base' failed
make[2]: *** [local-base] Error 2
make[2]: Leaving directory '/root/l2tp/libreswan-3.19/programs/pluto'
../mk/targets.mk:82: recipe for target 'recursive-all' failed
make[1]: *** [recursive-all] Error 2
make[1]: Leaving directory '/root/l2tp/libreswan-3.19/programs'
mk/targets.mk:82: recipe for target 'recursive-all' failed
make: *** [recursive-all] Error 2
libreswan-3.19 install failed.`

by reading the log , I found that I need to install "libsystemd-dev" instead of " libsystemd-daemon-dev" on my system.

`root@VPS:~# apt install libsystemd-daemon-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package libsystemd-daemon-dev is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  libsystemd-dev:i386 libsystemd-dev

E: Package 'libsystemd-daemon-dev' has no installation candidate
root@VPS:~# apt install libsystemd-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  libpam-systemd libsystemd0 systemd
Suggested packages:
  systemd-ui systemd-container
The following NEW packages will be installed:
  libsystemd-dev
The following packages will be upgraded:
  libpam-systemd libsystemd0 systemd
3 upgraded, 1 newly installed, 0 to remove and 31 not upgraded.
Need to get 4,102 kB of archives.
After this operation, 630 kB of additional disk space will be used.
Do you want to continue? [Y/n] `

So, suggest to add "libsystemd-dev" to the command on line 297 and 299. thanks~~

by the way, your scripts are real cool !

**Comment by Teddysun** [comment]
Thanks!
It's done.
