### ISSUE TITLE
CentOS 6 i686,libreswan install failed 

### ISSUE THREAD

**Issue by sunday123** [teddysun/across#92]
CentOS 6 i686 上的错误，CentOS7正常

**Comment by xianrennet** [comment]
您好，您的邮件已收到，我将尽快回复您。如是删除信息，我们将在5个工作日内处理，请尽量使用密码删除信息，如预留邮箱，可自助找回密码，不便之处敬请谅解。------------------------------本邮件为自动回复，谢谢！
